package com.focus.entity;
// Generated 2018-5-1 16:33:45 by Hibernate Tools 3.5.0.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Privilege generated by hbm2java
 */
@Entity
@Table(name = "privilege", catalog = "focus")
public class Privilege implements java.io.Serializable {

	private Integer id;
	private String priurl;
	private String priname;
	private Integer type;
	private String orderno;
	private String pridesc;
	private Set sysmenus = new HashSet(0);

	public Privilege() {
	}

	public Privilege(String priurl, String priname, Integer type, String orderno, String pridesc, Set sysmenus) {
		this.priurl = priurl;
		this.priname = priname;
		this.type = type;
		this.orderno = orderno;
		this.pridesc = pridesc;
		this.sysmenus = sysmenus;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "priurl", length = 200)
	public String getPriurl() {
		return this.priurl;
	}

	public void setPriurl(String priurl) {
		this.priurl = priurl;
	}

	@Column(name = "priname", length = 400)
	public String getPriname() {
		return this.priname;
	}

	public void setPriname(String priname) {
		this.priname = priname;
	}

	@Column(name = "type")
	public Integer getType() {
		return this.type;
	}

	public void setType(Integer type) {
		this.type = type;
	}

	@Column(name = "orderno", length = 10)
	public String getOrderno() {
		return this.orderno;
	}

	public void setOrderno(String orderno) {
		this.orderno = orderno;
	}

	@Column(name = "pridesc", length = 300)
	public String getPridesc() {
		return this.pridesc;
	}

	public void setPridesc(String pridesc) {
		this.pridesc = pridesc;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "privilege",targetEntity=Sysmenu.class)
	public Set getSysmenus() {
		return this.sysmenus;
	}

	public void setSysmenus(Set sysmenus) {
		this.sysmenus = sysmenus;
	}

}
