package com.focus.entity;
// Generated 2018-5-1 16:33:45 by Hibernate Tools 3.5.0.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Sysmenu generated by hbm2java
 */
@Entity
@Table(name = "sysmenu", catalog = "focus")
public class Sysmenu implements java.io.Serializable {

	private Integer id;
	private Privilege privilege;
	private Sysmenu sysmenu;
	private String menuname;
	private Integer orderno;
	private String rolename;
	private Set sysmenus = new HashSet(0);

	public Sysmenu() {
	}


	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "priid")
	public Privilege getPrivilege() {
		return this.privilege;
	}

	public void setPrivilege(Privilege privilege) {
		this.privilege = privilege;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "parentid")
	public Sysmenu getSysmenu() {
		return this.sysmenu;
	}

	public void setSysmenu(Sysmenu sysmenu) {
		this.sysmenu = sysmenu;
	}

	@Column(name = "menuname", length = 200)
	public String getMenuname() {
		return this.menuname;
	}

	public void setMenuname(String menuname) {
		this.menuname = menuname;
	}

	
	@Column(name = "orderno", length = 10)
	public Integer getOrderno() {
		return orderno;
	}

	public void setOrderno(Integer orderno) {
		this.orderno = orderno;
	}

	@Column(name = "rolename", length = 300)
	public String getRolename() {
		return this.rolename;
	}

	public void setRolename(String rolename) {
		this.rolename = rolename;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sysmenu",targetEntity=Sysmenu.class)
	public Set getSysmenus() {
		return this.sysmenus;
	}

	public void setSysmenus(Set sysmenus) {
		this.sysmenus = sysmenus;
	}


}
